/**
 * Script to generate environment.ts files from environment variables
 * Usage: node scripts/set-env.js [--production]
 * 
 * In production mode (--production):
 *   - Reads from .env.prod or process.env
 *   - Generates both environment.ts and environment.prod.ts with production credentials
 * 
 * In development mode (no flag):
 *   - Reads from .env
 *   - Generates only environment.ts with development credentials
 */

const fs = require('fs');
const path = require('path');

const isProduction = process.argv.includes('--production');

// Load environment variables from .env file if it exists
function loadEnvFile(filePath) {
    const envVars = {};
    if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');
        content.split('\n').forEach(line => {
            const trimmed = line.trim();
            if (trimmed && !trimmed.startsWith('#')) {
                const [key, ...valueParts] = trimmed.split('=');
                const value = valueParts.join('=');
                if (key && value !== undefined) {
                    envVars[key.trim()] = value.trim();
                }
            }
        });
        console.log(`✓ Loaded environment variables from ${filePath}`);
    } else {
        console.log(`! No ${filePath} found, using process.env variables`);
    }
    return envVars;
}

// Get environment variables (from file or process.env)
function getEnvConfig(envFile) {
    const envPath = path.join(__dirname, '..', envFile);
    const fileVars = loadEnvFile(envPath);

    return {
        apiKey: fileVars.NG_APP_FIREBASE_API_KEY || process.env.NG_APP_FIREBASE_API_KEY || '',
        authDomain: fileVars.NG_APP_FIREBASE_AUTH_DOMAIN || process.env.NG_APP_FIREBASE_AUTH_DOMAIN || '',
        projectId: fileVars.NG_APP_FIREBASE_PROJECT_ID || process.env.NG_APP_FIREBASE_PROJECT_ID || '',
        storageBucket: fileVars.NG_APP_FIREBASE_STORAGE_BUCKET || process.env.NG_APP_FIREBASE_STORAGE_BUCKET || '',
        messagingSenderId: fileVars.NG_APP_FIREBASE_MESSAGING_SENDER_ID || process.env.NG_APP_FIREBASE_MESSAGING_SENDER_ID || '',
        appId: fileVars.NG_APP_FIREBASE_APP_ID || process.env.NG_APP_FIREBASE_APP_ID || '',
        measurementId: fileVars.NG_APP_FIREBASE_MEASUREMENT_ID || process.env.NG_APP_FIREBASE_MEASUREMENT_ID || ''
    };
}

// Validate required variables
function validateEnvConfig(envConfig, envName) {
    const missingVars = Object.entries(envConfig)
        .filter(([key, value]) => !value)
        .map(([key]) => `NG_APP_FIREBASE_${key.toUpperCase()}`);

    if (missingVars.length > 0) {
        console.error(`✗ Missing required environment variables for ${envName}:`);
        missingVars.forEach(v => console.error(`  - ${v}`));
        return false;
    }
    return true;
}

// Generate environment file content
function generateEnvFileContent(envConfig, production) {
    return `// This file is auto-generated by scripts/set-env.js
// Do not edit manually - changes will be overwritten

import packageInfo from '../../package.json';

export const environment = {
  appVersion: packageInfo.version,
  production: ${production},
  firebase: {
    apiKey: "${envConfig.apiKey}",
    authDomain: "${envConfig.authDomain}",
    projectId: "${envConfig.projectId}",
    storageBucket: "${envConfig.storageBucket}",
    messagingSenderId: "${envConfig.messagingSenderId}",
    appId: "${envConfig.appId}",
    measurementId: "${envConfig.measurementId}"
  }
};
`;
}

// Write environment file
function writeEnvFile(environmentsDir, fileName, content) {
    const filePath = path.join(environmentsDir, fileName);
    fs.writeFileSync(filePath, content);
    console.log(`✓ Generated ${filePath}`);
}

// Ensure directory exists
const environmentsDir = path.join(__dirname, '..', 'src', 'environments');
if (!fs.existsSync(environmentsDir)) {
    fs.mkdirSync(environmentsDir, { recursive: true });
}

if (isProduction) {
    // Production mode: generate both files with production credentials
    console.log('\n📦 Production mode: generating both environment files with production credentials\n');

    const prodConfig = getEnvConfig('.env.prod');

    if (!validateEnvConfig(prodConfig, 'production')) {
        process.exit(1);
    }

    // Generate both files with production credentials (Angular needs both for file replacement)
    writeEnvFile(environmentsDir, 'environment.ts', generateEnvFileContent(prodConfig, false));
    writeEnvFile(environmentsDir, 'environment.prod.ts', generateEnvFileContent(prodConfig, true));

    console.log(`\n✓ Both environment files generated with production credentials`);
} else {
    // Development mode: generate only environment.ts with dev credentials
    console.log('\n🔧 Development mode: generating environment.ts with development credentials\n');

    const devConfig = getEnvConfig('.env');

    if (!validateEnvConfig(devConfig, 'development')) {
        process.exit(1);
    }

    writeEnvFile(environmentsDir, 'environment.ts', generateEnvFileContent(devConfig, false));

    // Also generate environment.prod.ts if it doesn't exist (needed for build to work)
    const prodEnvPath = path.join(environmentsDir, 'environment.prod.ts');
    if (!fs.existsSync(prodEnvPath)) {
        writeEnvFile(environmentsDir, 'environment.prod.ts', generateEnvFileContent(devConfig, true));
        console.log('  (placeholder for build compatibility)');
    }

    console.log(`\n✓ Development environment file generated`);
}
