/**
 * Script to generate environment.ts files from environment variables
 * Usage: node scripts/set-env.js [--production]
 */

const fs = require('fs');
const path = require('path');

const isProduction = process.argv.includes('--production');
const envFile = isProduction ? '.env.prod' : '.env';
const envPath = path.join(__dirname, '..', envFile);

// Load environment variables from .env file if it exists (for local development)
function loadEnvFile(filePath) {
    if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');
        content.split('\n').forEach(line => {
            const trimmed = line.trim();
            if (trimmed && !trimmed.startsWith('#')) {
                const [key, ...valueParts] = trimmed.split('=');
                const value = valueParts.join('=');
                if (key && value !== undefined) {
                    process.env[key.trim()] = value.trim();
                }
            }
        });
        console.log(`✓ Loaded environment variables from ${filePath}`);
    } else {
        console.log(`! No ${filePath} found, using process.env variables`);
    }
}

// Load from .env file (for local development)
loadEnvFile(envPath);

// Environment configuration
const envConfig = {
    apiKey: process.env.NG_APP_FIREBASE_API_KEY || '',
    authDomain: process.env.NG_APP_FIREBASE_AUTH_DOMAIN || '',
    projectId: process.env.NG_APP_FIREBASE_PROJECT_ID || '',
    storageBucket: process.env.NG_APP_FIREBASE_STORAGE_BUCKET || '',
    messagingSenderId: process.env.NG_APP_FIREBASE_MESSAGING_SENDER_ID || '',
    appId: process.env.NG_APP_FIREBASE_APP_ID || '',
    measurementId: process.env.NG_APP_FIREBASE_MEASUREMENT_ID || ''
};

// Validate required variables
const missingVars = Object.entries(envConfig)
    .filter(([key, value]) => !value)
    .map(([key]) => `NG_APP_FIREBASE_${key.toUpperCase()}`);

if (missingVars.length > 0) {
    console.error('✗ Missing required environment variables:');
    missingVars.forEach(v => console.error(`  - ${v}`));
    process.exit(1);
}

// Generate environment file content
function generateEnvFileContent(production) {
    return `// This file is auto-generated by scripts/set-env.js
// Do not edit manually - changes will be overwritten

import packageInfo from '../../package.json';

export const environment = {
  appVersion: packageInfo.version,
  production: ${production},
  firebase: {
    apiKey: "${envConfig.apiKey}",
    authDomain: "${envConfig.authDomain}",
    projectId: "${envConfig.projectId}",
    storageBucket: "${envConfig.storageBucket}",
    messagingSenderId: "${envConfig.messagingSenderId}",
    appId: "${envConfig.appId}",
    measurementId: "${envConfig.measurementId}"
  }
};
`;
}

// Write environment files
const environmentsDir = path.join(__dirname, '..', 'src', 'environments');

// Ensure directory exists
if (!fs.existsSync(environmentsDir)) {
    fs.mkdirSync(environmentsDir, { recursive: true });
}

// Generate only the appropriate environment file based on --production flag
if (isProduction) {
    const prodEnvPath = path.join(environmentsDir, 'environment.prod.ts');
    fs.writeFileSync(prodEnvPath, generateEnvFileContent(true));
    console.log(`✓ Generated ${prodEnvPath}`);
} else {
    const devEnvPath = path.join(environmentsDir, 'environment.ts');
    fs.writeFileSync(devEnvPath, generateEnvFileContent(false));
    console.log(`✓ Generated ${devEnvPath}`);
}

console.log(`\n✓ Environment file generated successfully (${isProduction ? 'production' : 'development'} mode)`);
